---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.kubeassemble.cn
  resources:
  - guides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.kubeassemble.cn
  resources:
  - guides/finalizers
  verbs:
  - update
- apiGroups:
  - test.kubeassemble.cn
  resources:
  - guides/status
  verbs:
  - get
  - patch
  - update
